#import <UIKit/UIKit.h>
#import <WebKit/WebKit.h>
#import <objc/runtime.h>
@interface PHOverlayManager:NSObject
+ (instancetype)sharedManager;
@end
@interface PHCustomFiltersTarget:NSObject
+ (instancetype)sharedTarget;
- (void)hide:(id)s;
- (void)manage:(id)s;
@end
static char K1,K2;
static NSString *PHPath(void){NSString*h=NSHomeDirectory();NSDirectoryEnumerator*e=[NSFileManager.defaultManager enumeratorAtPath:h];NSString*p;while((p=[e nextObject]))if([p.lastPathComponent.lowercaseString isEqualToString:@"custom-filters.json"])return[h stringByAppendingPathComponent:p];return[h stringByAppendingPathComponent:@"Documents/custom-filters.json"];}
static id PHM(void){Class c=NSClassFromString(@"PHOverlayManager");return[c respondsToSelector:@selector(sharedManager)]?[c performSelector:@selector(sharedManager)]:nil;}
static WKWebView*PHW(void){id m=PHM();return[m valueForKey:@"highlightedWebView"];}
static UIViewController*PHI(void){id m=PHM();return[m valueForKey:@"inspectorViewController"];}
static NSMutableArray*PHLoad(void){NSData*d=[NSData dataWithContentsOfFile:PHPath()];if(!d)return[NSMutableArray array];id j=[NSJSONSerialization JSONObjectWithData:d options:NSJSONReadingMutableContainers error:nil];if([j isKindOfClass:NSDictionary.class])j=j[@"filters"];return[j isKindOfClass:NSArray.class]?[j mutableCopy]:[NSMutableArray array];}
static void PHSave(NSArray*a){NSString*p=PHPath();[[NSFileManager defaultManager]createDirectoryAtPath:p.stringByDeletingLastPathComponent withIntermediateDirectories:YES attributes:nil error:nil];NSData*d=[NSJSONSerialization dataWithJSONObject:@{@"version":@1, @"filters":a?:@[]} options:0 error:nil];[d writeToFile:p atomically:YES];}
static NSString*PHSelected(void){return @"(function(){var e=document.querySelector('[data-projetoh-selected=\\\"1\\\"]');if(!e)return '{}';function p(n){if(n.id)return '#'+CSS.escape(n.id);var a=[];while(n&&n.nodeType===1&&n!==document.body){var q=n.parentElement;if(!q)break;var s=[...q.children].filter(x=>x.tagName===n.tagName);a.unshift(n.tagName.toLowerCase()+':nth-of-type('+(s.indexOf(n)+1)+')');n=q}return a.join(' > ')}return JSON.stringify({selector:p(e)})})()";}
static void PHApply(void){WKWebView*w=PHW();if(!w)return;NSMutableArray*s=[NSMutableArray array];for(NSDictionary*f in PHLoad()){NSString*selector=f[@"selector"];if(![selector isKindOfClass:NSString.class]||!selector.length){NSDictionary*action=f[@"action"];if([action isKindOfClass:NSDictionary.class])selector=action[@"selector"];}if([selector isKindOfClass:NSString.class]&&selector.length)[s addObject:selector];}NSData*d=[NSJSONSerialization dataWithJSONObject:s options:0 error:nil];NSString*j=[[NSString alloc]initWithData:d encoding:NSUTF8StringEncoding]?:@"[]";NSString*js=[NSString stringWithFormat:@"(function(){document.querySelectorAll('[data-projetoh-hidden=\\\"1\\\"]').forEach(function(e){e.style.display=e.getAttribute('data-projetoh-prev-display')||'';e.removeAttribute('data-projetoh-hidden');e.removeAttribute('data-projetoh-prev-display')});(%@).forEach(function(s){try{document.querySelectorAll(s).forEach(function(e){e.setAttribute('data-projetoh-hidden','1');e.setAttribute('data-projetoh-prev-display',e.style.display||'');e.style.display='none'})}catch(x){}})})()",j];[w evaluateJavaScript:js completionHandler:nil];}
static void PHRestore(NSString*s){WKWebView*w=PHW();if(!w)return;NSData*d=[NSJSONSerialization dataWithJSONObject:@[s] options:0 error:nil];NSString*j=[[NSString alloc]initWithData:d encoding:NSUTF8StringEncoding]?:@"[]";NSString*js=[NSString stringWithFormat:@"(%@).forEach(function(s){try{document.querySelectorAll(s).forEach(function(e){e.style.display=e.getAttribute('data-projetoh-prev-display')||'';e.removeAttribute('data-projetoh-hidden');e.removeAttribute('data-projetoh-prev-display')})}catch(x){}})",j];[w evaluateJavaScript:js completionHandler:nil];}
static void PHHide(void){WKWebView*w=PHW();if(!w)return;[w evaluateJavaScript:PHSelected() completionHandler:^(id r,NSError*e){if(e||![r isKindOfClass:NSString.class])return;NSDictionary*i=[NSJSONSerialization JSONObjectWithData:[r dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];NSString*s=i[@"selector"];if(!s.length)return;NSMutableArray*a=PHLoad();BOOL ok=NO;for(NSDictionary*f in a){NSString*fs=f[@"selector"];if(![fs isKindOfClass:NSString.class]){NSDictionary*action=f[@"action"];if([action isKindOfClass:NSDictionary.class])fs=action[@"selector"];}if([fs isEqualToString:s]){ok=YES;break;}}if(!ok){[a addObject:@{@"selector":s}];PHSave(a);}PHApply();}];}
static NSString*PHFriendlyName(NSDictionary*f){NSString*s=f[@"selector"];if(![s isKindOfClass:NSString.class]||!s.length){NSDictionary*action=f[@"action"];if([action isKindOfClass:NSDictionary.class])s=action[@"selector"];}if(![s isKindOfClass:NSString.class]||!s.length)return @"Elemento oculto";if([s isEqualToString:@"[id=header]"]||[s isEqualToString:@"#header"])return @"Cabeçalho";if([s isEqualToString:@".q-page-sticky"])return @"Elementos fixos";NSArray*parts=[s componentsSeparatedByString:@">"];NSString*last=[parts.lastObject stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];NSRange pseudo=[last rangeOfString:@":"];if(pseudo.location!=NSNotFound)last=[last substringToIndex:pseudo.location];NSRange idr=[last rangeOfString:@"#"];if(idr.location!=NSNotFound&&idr.location+1<last.length)return[NSString stringWithFormat:@"Elemento #%@",[last substringFromIndex:idr.location+1]];NSRange cr=[last rangeOfString:@"."];if(cr.location!=NSNotFound&&cr.location+1<last.length)return[NSString stringWithFormat:@"Elemento .%@",[last substringFromIndex:cr.location+1]];if([last caseInsensitiveCompare:@"img"]==NSOrderedSame)return @"Imagem";if([last caseInsensitiveCompare:@"lottie-player"]==NSOrderedSame)return @"Lottie Player";if(last.length==2&&[last.lowercaseString hasPrefix:@"h"]&&[[NSCharacterSet decimalDigitCharacterSet] characterIsMember:[last characterAtIndex:1]])return[NSString stringWithFormat:@"Título (%@)",[last uppercaseString]];if([last caseInsensitiveCompare:@"p"]==NSOrderedSame)return @"Texto";if([last caseInsensitiveCompare:@"main"]==NSOrderedSame)return @"Conteúdo principal";if([last caseInsensitiveCompare:@"section"]==NSOrderedSame)return @"Seção";if([last caseInsensitiveCompare:@"table"]==NSOrderedSame)return @"Tabela";if([last caseInsensitiveCompare:@"button"]==NSOrderedSame)return @"Botão";if([last caseInsensitiveCompare:@"center"]==NSOrderedSame)return @"Área central";if(last.length>0&&last.length<40)return[NSString stringWithFormat:@"Elemento <%@>",last];return @"Elemento oculto";}
static void PHManage(void){UIViewController*v=PHI();if(!v)return;NSArray*a=PHLoad();UIAlertController*x=[UIAlertController alertControllerWithTitle:@"Elementos ocultos" message:[NSString stringWithFormat:@"%lu item(ns) em custom-filters.json",(unsigned long)a.count] preferredStyle:UIAlertControllerStyleAlert];for(NSDictionary*f in a){NSString*s=f[@"selector"];if(![s isKindOfClass:NSString.class]||!s.length){NSDictionary*action=f[@"action"];if([action isKindOfClass:NSDictionary.class])s=action[@"selector"];}NSString*name=PHFriendlyName(f);[x addAction:[UIAlertAction actionWithTitle:[NSString stringWithFormat:@"Reativar: %@",name] style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*q){NSMutableArray*c=PHLoad();NSIndexSet*z=[c indexesOfObjectsPassingTest:^BOOL(NSDictionary*d,NSUInteger n,BOOL*stop){NSString*ds=d[@"selector"];if(![ds isKindOfClass:NSString.class]||!ds.length){NSDictionary*action=d[@"action"];if([action isKindOfClass:NSDictionary.class])ds=action[@"selector"];}return[ds isEqual:s];}];[c removeObjectsAtIndexes:z];PHSave(c);PHRestore(s);}]];}if(a.count)[x addAction:[UIAlertAction actionWithTitle:@"Reativar todos" style:UIAlertActionStyleDestructive handler:^(__unused UIAlertAction*q){for(NSDictionary*f in PHLoad()){NSString*s=f[@"selector"];if(![s isKindOfClass:NSString.class]||!s.length){NSDictionary*action=f[@"action"];if([action isKindOfClass:NSDictionary.class])s=action[@"selector"];}if([s isKindOfClass:NSString.class]&&s.length)PHRestore(s);}PHSave(@[]);}]];[x addAction:[UIAlertAction actionWithTitle:@"Fechar" style:UIAlertActionStyleCancel handler:nil]];[v presentViewController:x animated:YES completion:nil];}
@implementation PHCustomFiltersTarget
+ (instancetype)sharedTarget{static id t;static dispatch_once_t o;dispatch_once(&o,^{t=[self new];});return t;}
- (void)hide:(id)s{PHHide();}
- (void)manage:(id)s{PHManage();}
@end
static void PHAdd(void){UIViewController*v=PHI();if(!v)return;UIButton*o=objc_getAssociatedObject(v,&K1);if(o)[o removeFromSuperview];UIButton*o2=objc_getAssociatedObject(v,&K2);if(o2)[o2 removeFromSuperview];[v.view layoutIfNeeded];UIView*panel=nil;for(UIView*sub in v.view.subviews.reverseObjectEnumerator){if(sub!=v.view&&fabs(sub.bounds.size.width-350.0)<2.0&&fabs(sub.bounds.size.height-430.0)<2.0){panel=sub;break;}}UIView*host=panel?:v.view;CGRect bounds=host.bounds;UIButton*h=[UIButton buttonWithType:UIButtonTypeSystem];UIButton*m=[UIButton buttonWithType:UIButtonTypeSystem];h.frame=CGRectMake(MAX(18.0,bounds.size.width-192.0),bounds.size.height-54.0,82.0,30.0);m.frame=CGRectMake(MAX(108.0,bounds.size.width-100.0),bounds.size.height-54.0,82.0,30.0);h.autoresizingMask=UIViewAutoresizingFlexibleLeftMargin|UIViewAutoresizingFlexibleTopMargin;m.autoresizingMask=UIViewAutoresizingFlexibleLeftMargin|UIViewAutoresizingFlexibleTopMargin;[h setTitle:@"Ocultar" forState:UIControlStateNormal];h.titleLabel.font=[UIFont systemFontOfSize:15 weight:UIFontWeightSemibold];[m setTitle:@"Ocultos" forState:UIControlStateNormal];m.titleLabel.font=[UIFont systemFontOfSize:15 weight:UIFontWeightSemibold];[h addTarget:PHCustomFiltersTarget.sharedTarget action:@selector(hide:) forControlEvents:UIControlEventTouchUpInside];[m addTarget:PHCustomFiltersTarget.sharedTarget action:@selector(manage:) forControlEvents:UIControlEventTouchUpInside];[host addSubview:h];[host addSubview:m];objc_setAssociatedObject(v,&K1,h,OBJC_ASSOCIATION_RETAIN_NONATOMIC);objc_setAssociatedObject(v,&K2,m,OBJC_ASSOCIATION_RETAIN_NONATOMIC);}
static void(*Orig)(id,SEL,NSString*);
static void Hook(id s,SEL c,NSString*d){if(Orig)Orig(s,c,d);dispatch_async(dispatch_get_main_queue(),^{PHAdd();});}
__attribute__((constructor))static void Init(void){dispatch_async(dispatch_get_main_queue(),^{Class c=NSClassFromString(@"PHInspectorViewController");Method m=class_getInstanceMethod(c,@selector(showSelectedWebElement:));if(!m)return;static dispatch_once_t o;dispatch_once(&o,^{Orig=(void(*)(id,SEL,NSString*))method_getImplementation(m);method_setImplementation(m,(IMP)Hook);});});}
