#import <UIKit/UIKit.h>
#import <WebKit/WebKit.h>
#import <objc/runtime.h>

/* ProjetoH V21 — generic; WebFrame custom-filters.json is the source of truth. */
static NSString *PH21FilterPath(void){static NSString*p;static dispatch_once_t once;dispatch_once(&once,^{NSString*h=NSHomeDirectory();NSDirectoryEnumerator*e=[NSFileManager.defaultManager enumeratorAtPath:h];NSString*r;while((r=[e nextObject]))if([r.lastPathComponent.lowercaseString isEqualToString:@"custom-filters.json"]){p=[h stringByAppendingPathComponent:r];break;}if(!p.length)p=[h stringByAppendingPathComponent:@"Documents/custom-filters.json"];});return p;}
static NSString *PH21MetadataPath(void){return [PH21FilterPath().stringByDeletingLastPathComponent stringByAppendingPathComponent:@"projetoh-metadata.json"];}
static NSArray *PH21Filters(void){NSData*d=[NSData dataWithContentsOfFile:PH21FilterPath()];id j=d?[NSJSONSerialization JSONObjectWithData:d options:NSJSONReadingMutableContainers error:nil]:nil;if([j isKindOfClass:NSDictionary.class])j=j[@"filters"];return [j isKindOfClass:NSArray.class]?j:@[];}
static BOOL PH21WriteFilters(NSArray*filters){NSDictionary*root=@{@"version":@1,@"filters":filters?:@[]};NSData*d=[NSJSONSerialization dataWithJSONObject:root options:NSJSONWritingPrettyPrinted|NSJSONWritingSortedKeys error:nil];return d&&[d writeToFile:PH21FilterPath() atomically:YES];}
static NSString *PH21Selector(NSDictionary*f){if(![f isKindOfClass:NSDictionary.class])return nil;id s=f[@"selector"];if([s isKindOfClass:NSString.class]&&[s length])return s;NSDictionary*a=[f[@"action"] isKindOfClass:NSDictionary.class]?f[@"action"]:nil;s=a[@"selector"];return [s isKindOfClass:NSString.class]&&[s length]?s:nil;}
static NSMutableDictionary *PH21Metadata(void){NSData*d=[NSData dataWithContentsOfFile:PH21MetadataPath()];id j=d?[NSJSONSerialization JSONObjectWithData:d options:NSJSONReadingMutableContainers error:nil]:nil;NSDictionary*e=[j isKindOfClass:NSDictionary.class]&&[j[@"elements"] isKindOfClass:NSDictionary.class]?j[@"elements"]:nil;return e?[e mutableCopy]:[NSMutableDictionary dictionary];}
static void PH21WriteMetadata(NSDictionary*elements){if(!elements.count){[NSFileManager.defaultManager removeItemAtPath:PH21MetadataPath() error:nil];return;}NSDictionary*root=@{@"version":@1,@"elements":elements};NSData*d=[NSJSONSerialization dataWithJSONObject:root options:NSJSONWritingPrettyPrinted|NSJSONWritingSortedKeys error:nil];if(d)[d writeToFile:PH21MetadataPath() atomically:YES];}
static NSString *PH21Trim(NSString*s){s=[s stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];return s.length?(s.length>30?[[s substringToIndex:30]stringByAppendingString:@"…"]:s):nil;}
static NSString *PH21Name(NSDictionary*m){NSString*t=[m[@"tag"] isKindOfClass:NSString.class]?[m[@"tag"] lowercaseString]:@"";if([t isEqualToString:@"lottie-player"])return @"Lottie Player";for(NSString*k in @[@"ariaLabel",@"text",@"title"]){NSString*v=PH21Trim([m[k] isKindOfClass:NSString.class]?m[k]:nil);if(v.length)return v;}NSString*v=PH21Trim([m[@"id"] isKindOfClass:NSString.class]?m[@"id"]:nil);if(v.length)return [NSString stringWithFormat:@"#%@",v];NSString*c=[m[@"className"] isKindOfClass:NSString.class]?m[@"className"]:@"";for(NSString*x in [c componentsSeparatedByCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet])if(x.length&&!([x hasPrefix:@"ng-"]||[x hasPrefix:@"css-"]||[x hasPrefix:@"sc-"]||[x hasPrefix:@"jsx-"])&&![x isEqualToString:@"active"]&&![x isEqualToString:@"selected"]&&![x isEqualToString:@"disabled"]){NSString*q=PH21Trim(x);if(q.length)return [NSString stringWithFormat:@".%@",q];}return t.length?[t uppercaseString]:@"Elemento Web";}
static NSMutableDictionary*PH21Pending;
static void PH21CaptureForWebView(WKWebView*web,void(^completion)(NSString*,NSDictionary*)){if(!web||!completion)return;NSString*js=@"(function(){var e=document.querySelector('[data-projetoh-selected=\\\"1\\\"]');if(!e)return '{}';function p(n){if(n.id)return '#'+CSS.escape(n.id);var a=[];while(n&&n.nodeType===1&&n!==document.body){var q=n.parentElement;if(!q)break;var same=[...q.children].filter(function(c){return c.tagName===n.tagName;});a.unshift(n.tagName.toLowerCase()+':nth-of-type('+(same.indexOf(n)+1)+')');n=q;}return a.join(' > ');}return JSON.stringify({selector:p(e),tag:e.tagName.toLowerCase(),id:e.id||'',className:typeof e.className==='string'?e.className:'',text:(e.innerText||e.textContent||'').trim().replace(/\\s+/g,' ').slice(0,180),ariaLabel:e.getAttribute('aria-label')||'',title:e.getAttribute('title')||''});})()";[web evaluateJavaScript:js completionHandler:^(id result,NSError*error){if(error||![result isKindOfClass:NSString.class])return;NSData*d=[(NSString*)result dataUsingEncoding:NSUTF8StringEncoding];NSDictionary*m=d?[NSJSONSerialization JSONObjectWithData:d options:0 error:nil]:nil;NSString*s=[m[@"selector"] isKindOfClass:NSString.class]?m[@"selector"]:nil;if(!s.length)return;NSMutableDictionary*e=[NSMutableDictionary dictionaryWithDictionary:m?:@{}];e[@"name"]=PH21Name(e);if(!PH21Pending)PH21Pending=[NSMutableDictionary dictionary];PH21Pending[s]=e;completion(s,e);}];}
static void PH21SyncSavedMetadata(void){NSArray*filters=PH21Filters();NSMutableDictionary*meta=PH21Metadata();NSMutableSet*live=[NSMutableSet set];for(NSDictionary*f in filters){NSString*s=PH21Selector(f);if(s.length)[live addObject:s];}for(NSString*s in meta.allKeys.copy)if(![live containsObject:s])[meta removeObjectForKey:s];[PH21Pending enumerateKeysAndObjectsUsingBlock:^(NSString*s,NSDictionary*m,BOOL*stop){if([live containsObject:s])meta[s]=m;}];PH21WriteMetadata(meta);for(NSString*s in PH21Pending.allKeys.copy)if([live containsObject:s])[PH21Pending removeObjectForKey:s];}
static id PH21CurrentWebView(id self){@try{return [self valueForKey:@"highlightedWebView"];}@catch(__unused NSException*e){return nil;}}
static id PH21Inspector(id self){@try{return [self valueForKey:@"inspectorViewController"];}@catch(__unused NSException*e){return nil;}}
static void PH21Swizzle(Class c,SEL a,SEL b){if(!c)return;Method x=class_getInstanceMethod(c,a),y=class_getInstanceMethod(c,b);if(x&&y)method_exchangeImplementations(x,y);}
@interface NSObject(PHV21)- (void)ph21_hideSelectedElement;- (void)ph21_savePendingFilters;- (void)ph21_showHiddenElements;- (void)ph21_render:(BOOL)hierarchyMode;@end
@implementation NSObject(PHV21)
- (void)ph21_hideSelectedElement{PH21CaptureForWebView(PH21CurrentWebView(self),^(__unused NSString*s,__unused NSDictionary*e){});[self ph21_hideSelectedElement];}
- (void)ph21_savePendingFilters{[self ph21_savePendingFilters];PH21SyncSavedMetadata();}
- (void)ph21_showHiddenElements{NSArray*filters=PH21Filters();UIViewController*vc=PH21Inspector(self);if(!vc){[self ph21_showHiddenElements];return;}NSMutableDictionary*meta=PH21Metadata();NSMutableDictionary*counts=[NSMutableDictionary dictionary];UIAlertController*a=[UIAlertController alertControllerWithTitle:@"Elementos ocultos" message:[NSString stringWithFormat:@"%lu item(ns) salvo(s) em custom-filters.json",(unsigned long)filters.count] preferredStyle:UIAlertControllerStyleActionSheet];for(NSDictionary*f in filters){NSString*s=PH21Selector(f);if(!s.length)continue;NSString*n=PH21Name(meta[s]);if(!n.length)n=@"Elemento Web";NSInteger num=[counts[n]integerValue]+1;counts[n]=@(num);if(num>1)n=[NSString stringWithFormat:@"%@ #%ld",n,(long)num];[a addAction:[UIAlertAction actionWithTitle:[NSString stringWithFormat:@"Reativar: %@",n] style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){NSMutableArray*cur=[PH21Filters() mutableCopy];NSIndexSet*idx=[cur indexesOfObjectsPassingTest:^BOOL(NSDictionary*item,NSUInteger i,BOOL*stop){return [PH21Selector(item)isEqualToString:s];}];[cur removeObjectsAtIndexes:idx];if(PH21WriteFilters(cur)){PH21SyncSavedMetadata();[self ph21_render:NO];}}]];}if(filters.count)[a addAction:[UIAlertAction actionWithTitle:@"Reativar todos" style:UIAlertActionStyleDestructive handler:^(__unused UIAlertAction*x){if(PH21WriteFilters(@[])){PH21SyncSavedMetadata();[self ph21_render:NO];}}]];[a addAction:[UIAlertAction actionWithTitle:@"Fechar" style:UIAlertActionStyleCancel handler:nil]];a.popoverPresentationController.sourceView=vc.view;a.popoverPresentationController.sourceRect=vc.view.bounds;[vc presentViewController:a animated:YES completion:nil];}
- (void)ph21_render:(BOOL)h{[self ph21_render:h];UIViewController*vc=PH21Inspector(self);if(!vc)return;UIButton*hide=nil,*hidden=nil;for(UIView*v in vc.view.subviews){for(UIView*w in (v.subviews.count?v.subviews:@[v]))if([w isKindOfClass:UIButton.class]){NSString*t=[(UIButton*)w titleForState:UIControlStateNormal];if([t isEqualToString:@"Ocultar"])hide=(UIButton*)w;else if([t isEqualToString:@"Ocultos"])hidden=(UIButton*)w;}}if(hide&&hidden){[hide removeTarget:vc action:@selector(hideTapped) forControlEvents:UIControlEventTouchUpInside];[hidden removeTarget:vc action:@selector(hiddenTapped) forControlEvents:UIControlEventTouchUpInside];[hide setTitle:@"Ocultos" forState:UIControlStateNormal];[hidden setTitle:@"Ocultar" forState:UIControlStateNormal];[hide addTarget:vc action:@selector(hiddenTapped) forControlEvents:UIControlEventTouchUpInside];[hidden addTarget:vc action:@selector(hideTapped) forControlEvents:UIControlEventTouchUpInside];}}
@end
__attribute__((constructor))static void PHV21Init(void){PH21Pending=[NSMutableDictionary dictionary];dispatch_async(dispatch_get_main_queue(),^{Class c=NSClassFromString(@"PHOverlayManager");if(!c)return;PH21Swizzle(c,@selector(hideSelectedElement),@selector(ph21_hideSelectedElement));PH21Swizzle(c,@selector(savePendingFilters),@selector(ph21_savePendingFilters));PH21Swizzle(c,@selector(showHiddenElements),@selector(ph21_showHiddenElements));PH21Swizzle(NSClassFromString(@"PHInspectorViewController"),@selector(render:),@selector(ph21_render:));});}
