from pathlib import Path
p=Path('Sources/PHOverlayManager.m')
s=p.read_text(encoding='utf-8')
s=s.replace('s.componentsSeparatedByString:@" "][0]','[s componentsSeparatedByString:@" "].firstObject')
s=s.replace('s.componentsSeparatedByString:@" "][0]','[s componentsSeparatedByString:@" "].firstObject')
s=s.replace('s.componentsSeparatedByString:@" "][0]','[s componentsSeparatedByString:@" "].firstObject')
s=s.replace('@{@"trigger":@{@"url-filter":@".*"},@"action":@{@"type":@"css-display-none",@"selector":s}}','@{@"trigger":@{@"url-filter":@".*"}, @"action":@{@"type":@"css-display-none", @"selector":s}}')
s=s.replace('@{@"trigger":@{@"url-filter":@".*"},@"action":@{@"type":@"css-display-none",@"selector":selector}}','@{@"trigger":@{@"url-filter":@".*"}, @"action":@{@"type":@"css-display-none", @"selector":selector}}')
s=s.replace('@"Reativar: %@\\n%@"','@"Reativar: %@ — %@"')
s=s.replace('@"…"','@"..."')
s=s.replace('- (void)restoreInspector;','- (void)restoreInspector;\n- (void)applyKnownWebViews;\n- (void)savePendingFilters;\n- (void)showHiddenElements;\n- (void)hideSelectedElement;')
s=s.replace('- (void)showSelectedView:(UIView *)view;','- (void)showSelectedView:(UIView *)view;\n- (void)render:(BOOL)hierarchyMode;')
p.write_text(s,encoding='utf-8')
